enable service token role validation for all service tokens
openstack-k8s-operators/cinder-operator pull request #266
Opened 2023-09-15 13:26 UTC by SeanMooney

As part of adressing CVE-2023-2088 cinder was modifed to
require the service role to be present in service token when
calling the attachemtn api to modify attachments related to nova
instance. One recomendation of that CVE mitigration discussions
was that all services shoudl enabel the service token role validation
by default. This change simplely enabled that by setting
[keystone_authtoken]/service_token_roles_required = true

Related: OSPRH191

2023-09-19 20:08 UTC, ASBishop requested changes

2023-09-19 20:08 UTC, ASBishop commented on templates/cinderapi/config/01-service-defaults.conf
> +service_token_roles_required = true
Looks like this needs a newline.

2023-09-20 11:44 UTC, SeanMooney commented on templates/cinderapi/config/01-service-defaults.conf
> +service_token_roles_required = true
i guess i did not activate the venv when committing. i have precommet but it only runs if i have the venv activated
ill respin this shortly

2023-09-20 12:05 UTC, Akrog requested changes
Thank you for keeping an eye on this, though we already have it. :-)

2023-09-20 12:05 UTC, Akrog commented on templates/cinderapi/config/01-service-defaults.conf
> +service_token_roles_required = true
We already added this in [PR#257](https://github.com/openstack-k8s-operators/cinder-operator/pull/257/files) and it can be seen here (without the CVE related comment): https://github.com/openstack-k8s-operators/cinder-operator/blob/e8e5fb3c23c3a6271d48db593ad89e2f9ea43c1a/templates/cinder/config/00-global-defaults.conf#L66

If I remember correctly the cinder CVE code doesn't really need that option, it has an additional internal check so it wouldn't have to depend on this config option. I enabled this option in my PR anyway because I like the keystone middleware being the one that gives the error..

2023-09-20 12:52 UTC, SeanMooney commented on templates/cinderapi/config/01-service-defaults.conf
> +service_token_roles_required = true
oh cool in that case ill abandon this pr

2023-09-20 12:53 UTC, SeanMooney commented
fixed by #257

2023-09-20 12:53 UTC, closed without merging