Enable caching using memcached
openstack-k8s-operators/cinder-operator pull request #286
Opened 2023-10-25 16:20 UTC by ASBishop

Jira: OSP-26501

2023-10-26 21:21 UTC, ASBishop commented
/hold

I need to verify something

2023-10-27 12:32 UTC, Akrog requested changes
The code looks good, but it is making the deployment of memcached a hard requirement.
I would prefer an approach that would make it optional, for example when the `memcachedInstance` is set to an empty string the `enabled` in the global-defaults is set to `false`.

2023-10-27 12:32 UTC, Akrog commented on controllers/cinder_controller.go
> +	mc *memcachedv1.Memcached,
nit: Wouldn't it make it more readable using `memcached` instead of `mc`?

2023-10-27 13:37 UTC, ASBishop reviewed
While I don't know exactly where the discussion took place, my understanding is memcached is a required component (just as it is in tripleo). I recall seeing (but cannot find) a comment in another operator's PR that it is not necessary, at least at this juncture, to provide support for conditionally configuring memcached. See also https://issues.redhat.com/browse/OSP-26273

2023-10-27 15:02 UTC, ASBishop commented
/unhold

2023-11-01 17:33 UTC, ASBishop commented
/retest

'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1129)'

2023-11-01 20:16 UTC, ASBishop commented
/unhold

2023-11-06 10:23 UTC, Akrog approved these changes
/lgtm

2023-11-06 11:27 UTC, merged