WIP: cleaner kolla config
openstack-k8s-operators/cinder-operator pull request #43
Opened 2022-09-23 07:14 UTC by olliewalsh

2022-09-23 11:05 UTC, olliewalsh commented on templates/cinderbackup/config/kolla-config.json
> +  {{if .ServiceDebug}}
Maybe instead of a conditional just have a "ServiceCommand" var that if set will override the default?

2022-09-23 11:41 UTC, olliewalsh commented on pkg/cinder/const.go
> +	KollaDefaultProbeCommand = "/usr/local/bin/container-scripts/healthcheck.py backup"
for the api services the runs as root maybe run `sudo -u cinder -E ...`?

2022-09-23 11:48 UTC, olliewalsh commented on pkg/cinder/const.go
> +	KollaDefaultProbeCommand = "/usr/local/bin/container-scripts/healthcheck.py backup"
or the healthcheck script could setuid to cinder

2022-09-27 11:03 UTC, Akrog requested changes
I'm in agreement with the direction of the implementation, but there is an issue with the actual implementation, as it breaks Ceph deployments.

2022-10-06 09:53 UTC, olliewalsh commented on pkg/cinderbackup/statefulset.go
> +		VolumeMounts:         GetInitVolumeMounts(instance.Name),
Can stay with the previous name. The mount name was `config-data-custom` but will now provide more than the custom .conf so just wanted to make that a bit clearer.

2022-10-06 10:00 UTC, Akrog commented on pkg/cinderbackup/statefulset.go
> +		VolumeMounts:         GetInitVolumeMounts(instance.Name),
If you refer to how it now provides the command to run as well, then I agree that changing the name from `config-data-custom` to something like `config-data` is better. I'm just not sure of the benefit of prefixing it with the instance name as well.
In any case this is not a blocker, just an observation.

2024-03-14 19:00 UTC, Akrog commented
We no longer support the debug struct that required the different commands (we now use `oc debug`), so this PR seems to be no longer needed.

2024-03-14 19:00 UTC, closed without merging